### ISSUE TITLE
Error on theme install

### ISSUE THREAD

**Issue by madebymats** [jploch/FieldtypePageGrid#2]
I installed the PAGEGRID theme on MAMP and got this error:

`SQLSTATE[HY000]: General error: 1273 Unknown collation: 'utf8mb4_0900_ai_ci`

The installation seems to work just wanted to know about the error.'

PAGEGRID looks amazing! Great job!

**Comment by jploch** [comment]
Thanks for reporting this. 
What option did you choose when installing the theme/profile for "DB Charset"?
You have to choose "utf8" (default) instead of  "utf8mb4". Maybe I can try to force this in the future.

**Comment by jploch** [comment]
I updated the theme to force the utf8 charset. Please reopen if you are still having problems
