### ISSUE TITLE
PHP warnings after clean install

### ISSUE THREAD

**Issue by incognitoms** [jploch/FieldtypePageGrid#3]
Today I purchased a license to evaluate PageGrid for an upcoming project. I have created a new instance of ProcessWire 3.0.229 (latest master) from scratch and installed the FieldtypePageGrid module.

After install I see the following two warnings at the top of the admin (backend) and in the frontend as well. The instance is in debug mode ($config->debug = true).

Warning: Attempt to read property "name" on null in /var/www/web/wire/modules/Page/PageFrontEdit/PageFrontEdit.module on line 139

Warning: Attempt to read property "contentType" on null in /var/www/web/wire/modules/Page/PageFrontEdit/PageFrontEdit.module on line 146

![Bildschirmfoto 2024-04-02 um 20 47 13](https://github.com/jploch/FieldtypePageGrid/assets/7930439/1c322f4e-984b-4e07-bc03-b9c245617fce)

**Comment by jploch** [comment]
Thank you for your purchase of PAGEGRID!

Unfortunately I could not reproduce your error. I just did a test with a new installation of ProcessWire (latest master, 3.0.229). 

The error seems to affect the core module PageFrontEdit (PAGEGRID uses it for the inline editing). Can you check if the module is installed under **modules->core->PageFrontEdit**. This should actually be installed by PAGEGRID automatically, but maybe something went wrong here. If the module is installed try to save the PAGEGRID module modules->site->FieldtypePageGrid (submit button).

If that is not fixing your issue. Please provide more information about your server environment.

**Comment by incognitoms** [comment]
Thanks for your fast reply! I installed ProcessWire is 3.0.229 (latest master), like you did. You didn't mention if you enabled the debug mode, so I guess that makes a difference here.

I enabled debug mode ($config->debug = true) and the errors are shown. If the debug mode is disabled, no errors are visible.

PageFrontEdit is enabled.

**Comment by jploch** [comment]
The debug mode is enabled, but no errors occur. I have tested it on my local development environment. I will test it on a live server later. Which PHP version and hosting provider do you use?

I have also released an update for the module. Maybe you can try if it fixes your error?
Also which fields do you have enabled under setup->pagegrid->inline editor?

**Comment by incognitoms** [comment]
The instance is running on one of our development root servers with PHP 8.3 (I also tested PHP 8.2 with the same result). I deleted the instance completely, recreated ProcessWire 3.0.229 and installed FieldtypePageGrid. The version number is 2.0.41, but the error messages persist. I disabled the debug mode for now, which is fine for me, since we are just evaluating at the moment.

Talking about evaluation, I hope I don't bother you with too many questions, since this is GitHub and no support channel. I tried to create a second instance of a PageGrid field and bind that to the same template which already has a PageGrid field. But this doesn't work: 

> Fatal Error: Cannot redeclare createUnitField() (previously declared in site/modules/FieldtypePageGrid/stylePanel.php:1295) (line 1295 of site/modules/FieldtypePageGrid/stylePanel.php)

The idea behind using multiple PageGrid fields is to use PageGrid for certain parts of a page. I suppose the concept behind PageGrid is different – it's meant to be always used for the whole page, right?

**Comment by jploch** [comment]
Currently, there is no support for multiple PAGEGRID fields per template (See [docs](https://page-grid.com/docs/#/developer/functions)). You could create two templates with one field each and then render them inside one of your templates. Since PAGEGRID can have groups/containers of pages you might be fine with just one field. So far I haven't had a need for more than one field per page, but maybe you can explain your use case a bit as this might be something I will support at some point. 

Regarding the error: I will do some more tests and see if I can reproduce and fix the error. Will keep you updated here. Sorry for the inconvinience and the rogh start.

Also which fields do you have enabled under setup->pagegrid->inline editor?

**Comment by jploch** [comment]
@incognitoms I tested a new installation on my server again and still could not reproduce the error. Is the inline editor working for you? When you double click a text field it should let you edit the text. If the warnings you are seeing are not affecting the functionality, I would close this for now.

**Comment by incognitoms** [comment]
Thanks for your effort and especially for pointing me to the inline editor. As I know now, the inline editor does not work on our dev servers. I already started to wonder why there is a text saying "double click to edit" and nothing happened (I was only able to change the text in the right editor bar) :)

In the meantime, I installed ProcessWire in a docker environment on my local machine, and this works flawlessly. A whole new user experience! Now I have to do my homework and find out why it's not working on the dev servers, there must be some difference regarding the configuration. I'll keep you informed when I find something relevant to PageGrid.

Sorry for bothering you and have a nice weekend. I'll close this issue.

**Comment by incognitoms** [comment]
I attempted to reproduce the problem related to the PHP errors and conducted several tests. I discovered that the errors are triggered when a username other than "admin" is used during the ProcessWire installation process. In other words, if you use a different username like "admin2", the problem arises.

![install](https://github.com/jploch/FieldtypePageGrid/assets/7930439/e0e061db-063e-44a8-b2bb-95972859a032)

This issue can also be simply reproduced with an already existing ProcessWire instance by editing the "admin" user and renaming the username to "admin2". After this change, PHP errors should become visible if you're in debug mode:

> Warning: Attempt to read property "name" on null in /var/www/html/wire/modules/Page/PageFrontEdit/PageFrontEdit.module on line 139
> 
> Warning: Attempt to read property "contentType" on null in /var/www/html/wire/modules/Page/PageFrontEdit/PageFrontEdit.module on line 146

**Comment by incognitoms** [comment]
The username "admin" is hardcoded in FieldtypePageGrid.module.php, line 585:
`$p = $this->pages->get('admin');`

**Comment by jploch** [comment]
Thank you for tracking down the issue. I just pushed a fix. Can you try if 2.0.44 is fixing it.

**Comment by incognitoms** [comment]
Yes, this release is fixing the issue. Thanks a lot!
